#!/usr/bin/env python3
"""Run the D2(c) sequential-vs-parallel comparison for REF-5602.

Usage:
    python run_d2c.py parallel
    python run_d2c.py sequential

The parallel condition is the existing REF-5602 script in backends.py.
The sequential condition keeps the same case, tools, arguments, decision,
and gate, but issues exactly one tool call per turn.  Both runs use the
scripted backend so the comparison is free and reproducible.
"""
import json
import sys

import backends
import config
from harness import report, run_set


CASE_ID = "REF-5602"


# This is deliberately written out rather than generated by splitting the
# parallel script.  It documents the dependency-respecting baseline used in
# the report: each tool observation is available before the next call starts.
SEQUENTIAL_REF_5602 = [
    {"thought": "Fetch the referral record.",
     "calls": [("get_referral", {"referral_id": CASE_ID})]},
    {"thought": "Check the specialty criteria before continuing.",
     "calls": [("check_referral_criteria",
                {"specialty": "OPH", "referral_id": CASE_ID})]},
    {"thought": "No stopping criterion was found; check for a duplicate appointment.",
     "calls": [("lookup_patient", {"patient_id": "P-1180"})]},
    {"thought": "Search the first half of the routine clinical window.",
     "calls": [("get_clinic_slots",
                {"specialty": "OPH", "band": "routine",
                 "from": "2026-09-09", "to": "2026-09-30"})]},
    {"thought": "The first half has no free slot; search the second half.",
     "calls": [("get_clinic_slots",
                {"specialty": "OPH", "band": "routine",
                 "from": "2026-10-01", "to": "2026-11-04"})]},
    {"thought": "A legal slot is available; pass the simulated write through the gate.",
     "calls": [("book_slot", {"clinic": "OPH-C2", "date": "2026-10-14",
                                 "time": "11:20", "referral_id": CASE_ID})]},
    {"final": {
        "decision": "book",
        "booked": {"clinic": "OPH-C2", "date": "2026-10-14", "time": "11:20"},
        "reason": "Urgency band routine, VF-01 present, and no existing OPH "
                  "appointment. OPH-C2 was first available on 2026-10-14 "
                  "inside the eight-week window.",
    }},
]


def main(argv):
    mode = argv[1].lower() if len(argv) == 2 else None
    if mode not in {"parallel", "sequential"}:
        raise SystemExit("Usage: python run_d2c.py parallel|sequential")
    if config.BACKEND != "scripted":
        raise SystemExit("Set BACKEND = 'scripted' in config.py before running D2(c).")

    # Preserve the normal evaluation scripts: this substitution lasts only
    # for this process and never edits backends.py.
    original = backends.SCRIPTS[CASE_ID]
    if mode == "sequential":
        backends.SCRIPTS[CASE_ID] = SEQUENTIAL_REF_5602

    try:
        print(config.summary())
        print("D2(c) mode: %s | case: %s\n" % (mode, CASE_ID))
        results, judgement_queue = run_set([CASE_ID], verbose=True)
        summary = report(results)
        filename = "d2c_%s_results.json" % mode
        with open(filename, "w", encoding="utf-8") as fh:
            json.dump({"mode": mode, "case": CASE_ID, "summary": summary,
                       "results": results, "judgement_queue": judgement_queue},
                      fh, indent=2, default=str)
        print("Wrote %s" % filename)
    finally:
        backends.SCRIPTS[CASE_ID] = original


if __name__ == "__main__":
    main(sys.argv)
